update location object and greenhouse
VMCvastry/jobseeker pull request #12
Opened 2023-08-22 21:11 UTC by riccardo1501

2023-08-26 21:22 UTC, VMCvastry requested changes
Non mi ha convinto tantissimo la nuova location ma mi fido hahah tua responsavilita ora

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/job.py
> +):
Ma mi spieghi perche io continuo a togliere queste righe e tu continui a rimetterle HAHAHAH, lascia il TODO per il momento, quelle parole son sbagliate, vanno controllate, tipo coop work sicuramente è sbaglaito, probabilmente è scritto co-op e probabilmente non è "coop work" ma qualcosa del genere. Quindi lascia il todo, invece stage lo puoi lasciare, trainership non lo so se viene utilizzato o no

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/location.py
> +STATE_NAMES = {
mettili in un file

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/job.py
> -    remote: bool
Perche lo togli? lascialo come avevamo messo lultima review. Anche nel post init io mi pare che avevo messo remote=isRemote(city) che fine ha fatto? é importante avere la flag remote

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/location.py
> +            self.log = logging.getLogger()
perche il logger sta dentro un else?

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/location.py
> +def exceptions(text):
Rinomina questa funzione "expandStateCode"

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/location.py
> +    if text == "nairobi":
eh?

2023-08-26 21:22 UTC, VMCvastry commented on backend/models/location.py
Se devo essere onesto non mi piace troppo questa nuova classe location, secondo me si rompe molto facilment, non si capisce bene cosa stia facendo ed è difficile da debuggare. Lavora troppo sulle stirnge e secondo me è molto probabile dia risultati inaspettati. Secondo me era meglio lasciarec ome stava prima. comuqnue per il momneto va bene poi semmai la refactorizziamo in futuro, mi fido funzioni ahahah.

2023-08-26 21:22 UTC, VMCvastry approved these changes

2023-08-27 15:19 UTC, riccardo1501 commented on backend/models/job.py
> +):
non lo faccio di proposito hahahaha

2023-08-27 15:34 UTC, closed without merging