Nic
VMCvastry/jobseeker pull request #21
Opened 2023-09-09 08:29 UTC by nicg03

- added some scrapers
- made is_internship method
- changed category enum class
- created class to handle category assignation
- changed parameters of some classes, some will be optional
- fixed errors in previous scrapers
- other small

2023-09-09 23:52 UTC, VMCvastry requested changes
Non mi piace molto il category parser, ti scrivo in privata

2023-09-09 23:52 UTC, VMCvastry commented on backend/scrapers/apple.py
> +            sys.exit()
che è sta sys.exit qui oh ahahahah. 
Questo è un suicidio hahahaha. uno scraper va in errore  e il main muore. Ritorna un errore e basta

2023-09-10 07:12 UTC, nicg03 commented on backend/scrapers/apple.py
> +            sys.exit()
Dato che la response è necessaria, come faccio a gestire questi errori?

2023-09-10 15:33 UTC, nicg03 reviewed
review

2023-09-12 05:44 UTC, VMCvastry approved these changes

2023-09-12 05:48 UTC, merged