aziende michela
VMCvastry/jobseeker pull request #6
Opened 2023-08-18 12:09 UTC by kela03

2023-08-20 06:55 UTC, VMCvastry requested changes
Solo un po' di commenti stilistici

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/amazon.py
> +                location_list = (j['location']).split(', ')
Le parentesi a che servono?

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/amazon.py
> +                print('city: ', city, 'country: ' ,country, 'title: ',j['title'])
Usa logging, e togli i print tipo hijii ahahah

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/amazon.py
> +                    print('hiiii')
If city virtual:
    City=remote

E poi dopo 
Location...

Così togli else ed è più pulito

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/amazon.py
> +                job = Job(category=j['job_category'], title=j['title'], company=j['company_name'], link=f'www.amazon.jobs{j["job_path"]}', locations=locations, data=data, internship= False)
Locations deve essere una lista, quindi fai locations=[location]

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/google.py
> +
```suggestion
                      internship = "Intern & Apprentice" in testo_lavoro

```

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/google.py
> +                        if 'Remote' in cities:
Da qui riga 43 a riga 60 non è chiarissimo cosa stia succedendo, prova a pulire il codice, dare nomi diversi e estrarre logica in funzioni e vedi se riesci a renderlo più leggibile. È una minuzia ma è un buon esercizio

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/google/google.py
> +            if "Intern & Apprentice" in testo_lavoro:
Same as above

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/google/google.py
> +            if "remote" in testo_lavoro:
Same

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/google/google.py
> +                r2 = requests.get(link)
Non usare variabili da una lettera (tranne i e j), e qui puoi fare direttamente .text, è più pulito

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/google.py
> +                        r2 = requests.get(link)
Commentato in un'altra scraper

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/microsoft.py
> +            jobs = r.json()['operationResult']['result']['jobs']
Inverti riga 18-19 con riga 20 e poi fai 
If(jobs)

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/microsoft.py
> +                if j['properties']['employmentType'] == 'Internship':
Same

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/microsoft.py
> +                        locations.append(loc)
Questo lo fai sia nel if che nel else, portalo fuori

2023-08-20 06:55 UTC, VMCvastry commented on scrapers/microsoft/microsoft.py
> +                        pass
Che succede qui?

2023-09-08 19:33 UTC, kela03 commented
aspetto ok per fare il merge

2023-09-10 00:03 UTC, VMCvastry approved these changes

2023-09-12 10:02 UTC, merged